services:
  - docker

env:
  global:
    - NAME=aria2-ui
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/${NAME}-${TRAVIS_COMMIT}.tgz

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t wahyd4/aria2-ui:2.0.${TRAVIS_BUILD_NUMBER} .
        - mkdir -p ${CACHE_FOLDER}
        - docker save wahyd4/aria2-ui:2.0.${TRAVIS_BUILD_NUMBER} | gzip -c > ${CACHE_FILE}
    - stage: push docker image
      if: branch = master
      script: |
        if [[ -f ${CACHE_FILE} ]]; then docker load -i ${CACHE_FILE}; fi
        if [ "${TRAVIS_BRANCH}" == "master" ]; then
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag wahyd4/aria2-ui:2.0.$TRAVIS_BUILD_NUMBER wahyd4/aria2-ui:latest
          docker push wahyd4/aria2-ui:2.0.$TRAVIS_BUILD_NUMBER
          docker push wahyd4/aria2-ui:latest
        fi

cache:
  directories:
    - ${CACHE_FOLDER}
